apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition
  namespace: {{ .Values.namespace }}
  labels:
    liqo.io/offloadable: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-recognition
  template:
    metadata:
      labels:
        app: image-recognition
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: liqo.io/type
                    operator: NotIn
                    values:
                      - virtual-node
      containers:
      - name: image-recognition
        image: oxhunt/image-recognition:latest
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_BROKER
          value: "mosquitto-service"
        volumeMounts:
        - name: yolomodel-volume
          mountPath: /yolomodel.pt
      volumes:
      - name: yolomodel-volume
        hostPath:
          path: {{ .Values.files_folder }}/yolo11n.pt
          type: File