---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-streamer
  template:
    metadata:
      labels:
        app: camera-streamer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: liqo.io/type
                    operator: NotIn
                    values:
                      - virtual-node
      containers:
      - name: camera-streamer
        image: oxhunt/camera-streamer:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          privileged: true
        env:
        - name: FPS
          value: "10"
        - name: VIDEO_TO_PLAY
          value: "/video.mp4"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_BROKER
          value: "mosquitto-service"
        volumeMounts:
        - mountPath: /dev/video0
          name: video0
        - mountPath: /dev/video1
          name: video1
        - name: fakevideo-volume
          mountPath: /video.mp4
      volumes:
      - name: fakevideo-volume
        hostPath:
          path: /home/ubuntu/FLUIDOS-Example/files/video-self-driving.mp4
      - name: video0
        hostPath:
          path: /dev/video0
      - name: video1
        hostPath:
          path: /dev/video1